// Auto-generated by tools/tag_pages.py
export const SCHEMA = {
 "index": {
  "title": "Home",
  "fields": [
   {
    "k": "t1",
    "tag": "span",
    "def": "✕"
   },
   {
    "k": "t2",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t3",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t4",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t5",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t6",
    "tag": "a",
    "def": "Consultation"
   },
   {
    "k": "t7",
    "tag": "p",
    "def": "Crisis Communication · Strategic PR · Reputation Management"
   },
   {
    "k": "t8",
    "tag": "h1",
    "def": "When the narrative is<br/>at stake, clarity is<br/><em>not optional.</em>"
   },
   {
    "k": "t9",
    "tag": "em",
    "def": "not optional."
   },
   {
    "k": "t10",
    "tag": "p",
    "def": "Voice Forte™ transforms high-pressure communication challenges into strategic advantage. Built on 13 years of frontline journalism — covering political crises, health emergencies, and institutional failures — we know how narratives break, and how to protect them."
   },
   {
    "k": "t11",
    "tag": "a",
    "def": "Request Strategy Session"
   },
   {
    "k": "t12",
    "tag": "a",
    "def": "+92 333 292 4941"
   },
   {
    "k": "t13",
    "tag": "div",
    "def": "13+"
   },
   {
    "k": "t14",
    "tag": "div",
    "def": "Years Journalism"
   },
   {
    "k": "t15",
    "tag": "div",
    "def": "1,000+"
   },
   {
    "k": "t16",
    "tag": "div",
    "def": "Published Stories"
   },
   {
    "k": "t17",
    "tag": "div",
    "def": "7+"
   },
   {
    "k": "t18",
    "tag": "div",
    "def": "GCC Market Expertise"
   },
   {
    "k": "t19",
    "tag": "div",
    "def": "SRMG"
   },
   {
    "k": "t20",
    "tag": "div",
    "def": "Saudi Media Published"
   },
   {
    "k": "t21",
    "tag": "div",
    "def": "🇵🇰 Pakistan"
   },
   {
    "k": "t22",
    "tag": "div",
    "def": "🇸🇦 Saudi Arabia"
   },
   {
    "k": "t23",
    "tag": "div",
    "def": "🇦🇪 UAE"
   },
   {
    "k": "t24",
    "tag": "div",
    "def": "🇶🇦 Qatar"
   },
   {
    "k": "t25",
    "tag": "div",
    "def": "🇰🇼 Kuwait"
   },
   {
    "k": "t26",
    "tag": "p",
    "def": "What We Do"
   },
   {
    "k": "t27",
    "tag": "h2",
    "def": "Services Built on<br/><em>Newsroom Precision</em>"
   },
   {
    "k": "t28",
    "tag": "em",
    "def": "Newsroom Precision"
   },
   {
    "k": "t29",
    "tag": "p",
    "def": "Every service is rooted in 13 years of breaking-news experience — where accuracy, speed, and credibility are non-negotiable."
   },
   {
    "k": "t30",
    "tag": "div",
    "def": "01"
   },
   {
    "k": "t31",
    "tag": "div",
    "def": "🛡️"
   },
   {
    "k": "t32",
    "tag": "h3",
    "def": "Crisis Communication Management"
   },
   {
    "k": "t33",
    "tag": "p",
    "def": "When a crisis breaks, every minute counts. We deploy rapid-response messaging frameworks to contain reputational damage, control the information cycle, and restore stakeholder confidence — before the story writes itself."
   },
   {
    "k": "t34",
    "tag": "span",
    "def": "Rapid Response"
   },
   {
    "k": "t35",
    "tag": "span",
    "def": "Dark Site Readiness"
   },
   {
    "k": "t36",
    "tag": "span",
    "def": "Holding Statements"
   },
   {
    "k": "t37",
    "tag": "span",
    "def": "24/7 Advisory"
   },
   {
    "k": "t38",
    "tag": "div",
    "def": "02"
   },
   {
    "k": "t39",
    "tag": "div",
    "def": "📖"
   },
   {
    "k": "t40",
    "tag": "h3",
    "def": "Strategic Narrative Design"
   },
   {
    "k": "t41",
    "tag": "p",
    "def": "Your institution has a story. We ensure it's told with authority. From positioning frameworks to long-form brand journalism, we craft narratives that define how governments, corporations, and executives are perceived."
   },
   {
    "k": "t42",
    "tag": "span",
    "def": "Message Architecture"
   },
   {
    "k": "t43",
    "tag": "span",
    "def": "Brand Journalism"
   },
   {
    "k": "t44",
    "tag": "span",
    "def": "Thought Leadership"
   },
   {
    "k": "t45",
    "tag": "span",
    "def": "Arabic Adaptation"
   },
   {
    "k": "t46",
    "tag": "div",
    "def": "03"
   },
   {
    "k": "t47",
    "tag": "div",
    "def": "🎙️"
   },
   {
    "k": "t48",
    "tag": "h3",
    "def": "Executive Media Training"
   },
   {
    "k": "t49",
    "tag": "p",
    "def": "Trained by a journalist who has interviewed ministers, covered disasters, and conducted investigations — our media training prepares executives for hostile press, live broadcast, and high-stakes stakeholder briefings."
   },
   {
    "k": "t50",
    "tag": "span",
    "def": "Mock Interviews"
   },
   {
    "k": "t51",
    "tag": "span",
    "def": "On-Camera Training"
   },
   {
    "k": "t52",
    "tag": "span",
    "def": "Press Conference Prep"
   },
   {
    "k": "t53",
    "tag": "span",
    "def": "Key Message Drills"
   },
   {
    "k": "t54",
    "tag": "div",
    "def": "04"
   },
   {
    "k": "t55",
    "tag": "div",
    "def": "📰"
   },
   {
    "k": "t56",
    "tag": "h3",
    "def": "Corporate Communications Strategy"
   },
   {
    "k": "t57",
    "tag": "p",
    "def": "We build end-to-end communication ecosystems — internal and external — ensuring your organization speaks with one coherent voice across all channels, audiences, and markets, from Karachi to Riyadh."
   },
   {
    "k": "t58",
    "tag": "span",
    "def": "Communication Audit"
   },
   {
    "k": "t59",
    "tag": "span",
    "def": "Policy Development"
   },
   {
    "k": "t60",
    "tag": "span",
    "def": "Stakeholder Mapping"
   },
   {
    "k": "t61",
    "tag": "span",
    "def": "Multi-Channel Strategy"
   },
   {
    "k": "t62",
    "tag": "div",
    "def": "05"
   },
   {
    "k": "t63",
    "tag": "div",
    "def": "🌐"
   },
   {
    "k": "t64",
    "tag": "h3",
    "def": "Reputation Management &amp; Monitoring"
   },
   {
    "k": "t65",
    "tag": "p",
    "def": "Proactive reputation management that detects threats before they escalate. We monitor media landscapes, identify narrative risks, and build long-term credibility infrastructure for organizations operating in complex environments."
   },
   {
    "k": "t66",
    "tag": "span",
    "def": "Media Monitoring"
   },
   {
    "k": "t67",
    "tag": "span",
    "def": "Sentiment Analysis"
   },
   {
    "k": "t68",
    "tag": "span",
    "def": "Risk Mapping"
   },
   {
    "k": "t69",
    "tag": "span",
    "def": "Counter-Narrative"
   },
   {
    "k": "t70",
    "tag": "div",
    "def": "06"
   },
   {
    "k": "t71",
    "tag": "div",
    "def": "🤝"
   },
   {
    "k": "t72",
    "tag": "h3",
    "def": "Media Relations &amp; Earned Coverage"
   },
   {
    "k": "t73",
    "tag": "p",
    "def": "We leverage 13+ years of journalist relationships across Pakistan's leading broadcast and print media to secure earned coverage — the most credible form of visibility money cannot simply buy."
   },
   {
    "k": "t74",
    "tag": "span",
    "def": "Press Release Strategy"
   },
   {
    "k": "t75",
    "tag": "span",
    "def": "Media Pitching"
   },
   {
    "k": "t76",
    "tag": "span",
    "def": "Broadcast Placement"
   },
   {
    "k": "t77",
    "tag": "span",
    "def": "Editorial Access"
   },
   {
    "k": "t78",
    "tag": "div",
    "def": "07"
   },
   {
    "k": "t79",
    "tag": "div",
    "def": "🏛️"
   },
   {
    "k": "t80",
    "tag": "h3",
    "def": "Public Affairs &amp; Government Relations"
   },
   {
    "k": "t81",
    "tag": "p",
    "def": "Navigating the interface between organizations and government requires credibility on both sides. Our background covering governors, ministers, and regulatory bodies gives us unique insight into institutional communication."
   },
   {
    "k": "t82",
    "tag": "span",
    "def": "Policy Messaging"
   },
   {
    "k": "t83",
    "tag": "span",
    "def": "Regulatory Affairs"
   },
   {
    "k": "t84",
    "tag": "span",
    "def": "Advocacy Communication"
   },
   {
    "k": "t85",
    "tag": "span",
    "def": "Institutional Briefings"
   },
   {
    "k": "t86",
    "tag": "div",
    "def": "08"
   },
   {
    "k": "t87",
    "tag": "div",
    "def": "🔍"
   },
   {
    "k": "t88",
    "tag": "h3",
    "def": "Investigative Intelligence &amp; Due Diligence"
   },
   {
    "k": "t89",
    "tag": "p",
    "def": "We apply the skills of investigative journalism — source development, document analysis, institutional research — to provide organizations with intelligence on reputational risks, third-party exposure, and sector vulnerabilities."
   },
   {
    "k": "t90",
    "tag": "span",
    "def": "Background Research"
   },
   {
    "k": "t91",
    "tag": "span",
    "def": "Risk Assessment"
   },
   {
    "k": "t92",
    "tag": "span",
    "def": "Sector Analysis"
   },
   {
    "k": "t93",
    "tag": "span",
    "def": "Narrative Auditing"
   },
   {
    "k": "t94",
    "tag": "div",
    "def": "09"
   },
   {
    "k": "t95",
    "tag": "div",
    "def": "📱"
   },
   {
    "k": "t96",
    "tag": "h3",
    "def": "Digital &amp; Social Media Communication"
   },
   {
    "k": "t97",
    "tag": "p",
    "def": "Strategic content systems and platform-specific audience engagement — built for the speed and scrutiny of today's information environment while maintaining institutional credibility."
   },
   {
    "k": "t98",
    "tag": "span",
    "def": "Content Strategy"
   },
   {
    "k": "t99",
    "tag": "span",
    "def": "Platform Management"
   },
   {
    "k": "t100",
    "tag": "span",
    "def": "Audience Engagement"
   },
   {
    "k": "t101",
    "tag": "span",
    "def": "Narrative Consistency"
   },
   {
    "k": "t102",
    "tag": "p",
    "def": "The Difference"
   },
   {
    "k": "t103",
    "tag": "p",
    "def": "Most PR firms advise on communication.<br/>We advise from experience inside the crisis — as the journalist on the other side."
   },
   {
    "k": "t104",
    "tag": "div",
    "def": "\"We don't just understand how institutions communicate. We understand how journalists <em>investigate</em> them — and that's a perspective no crisis ever gets to ignore.\""
   },
   {
    "k": "t105",
    "tag": "em",
    "def": "investigate"
   },
   {
    "k": "t106",
    "tag": "p",
    "def": "Founder Profile"
   },
   {
    "k": "t107",
    "tag": "h2",
    "def": "Rao Muhammad<br/><em>Afnan</em>"
   },
   {
    "k": "t108",
    "tag": "em",
    "def": "Afnan"
   },
   {
    "k": "t109",
    "tag": "p",
    "def": "Crisis Communication &amp; Corporate Communications Director with 13+ years spanning national broadcast journalism, investigative reporting, and strategic communications. Former senior correspondent at BOL News, Suno TV, and Daily Ummat. Published contributor to SRMG's Urdu News, Jeddah."
   },
   {
    "k": "t110",
    "tag": "p",
    "def": "Covered Pakistan's first COVID-19 case, the Kemari gas tragedy, Ghotki train disaster, Supreme Court demolitions, and PM-level political events live on air. Investigated university corruption, cyber crime, fake NADRA websites, and land fraud schemes."
   },
   {
    "k": "t111",
    "tag": "p",
    "def": "Primary Broadcast"
   },
   {
    "k": "t112",
    "tag": "p",
    "def": "BOL News"
   },
   {
    "k": "t113",
    "tag": "p",
    "def": "2019 – 2022 · On-site Karachi"
   },
   {
    "k": "t114",
    "tag": "p",
    "def": "Long-form Print"
   },
   {
    "k": "t115",
    "tag": "p",
    "def": "Daily Ummat"
   },
   {
    "k": "t116",
    "tag": "p",
    "def": "2013 – 2019 · 1,000+ Stories"
   },
   {
    "k": "t117",
    "tag": "p",
    "def": "Broadcast &amp; Field"
   },
   {
    "k": "t118",
    "tag": "p",
    "def": "Suno TV"
   },
   {
    "k": "t119",
    "tag": "p",
    "def": "2022 – 2025 · Senior Broadcast Journalist"
   },
   {
    "k": "t120",
    "tag": "p",
    "def": "GCC Published"
   },
   {
    "k": "t121",
    "tag": "p",
    "def": "SRMG · Jeddah"
   },
   {
    "k": "t122",
    "tag": "p",
    "def": "Urdu News · Saudi Arabia"
   },
   {
    "k": "t123",
    "tag": "p",
    "def": "Certification"
   },
   {
    "k": "t124",
    "tag": "p",
    "def": "Crisis Communication"
   },
   {
    "k": "t125",
    "tag": "p",
    "def": "IACET-Accredited · Saylor Academy 2026"
   },
   {
    "k": "t126",
    "tag": "p",
    "def": "Certification"
   },
   {
    "k": "t127",
    "tag": "p",
    "def": "Human Communication"
   },
   {
    "k": "t128",
    "tag": "p",
    "def": "IACET-Accredited · Saylor Academy 2026"
   },
   {
    "k": "t129",
    "tag": "p",
    "def": "Languages"
   },
   {
    "k": "t130",
    "tag": "p",
    "def": "Urdu"
   },
   {
    "k": "t131",
    "tag": "p",
    "def": "Native · Full Professional"
   },
   {
    "k": "t132",
    "tag": "p",
    "def": "English"
   },
   {
    "k": "t133",
    "tag": "p",
    "def": "Full Professional Proficiency"
   },
   {
    "k": "t134",
    "tag": "p",
    "def": "Arabic"
   },
   {
    "k": "t135",
    "tag": "p",
    "def": "Reading · GCC Media Familiarity"
   },
   {
    "k": "t136",
    "tag": "p",
    "def": "How We Work"
   },
   {
    "k": "t137",
    "tag": "h2",
    "def": "From Brief to<br/><em>Controlled Narrative</em>"
   },
   {
    "k": "t138",
    "tag": "em",
    "def": "Controlled Narrative"
   },
   {
    "k": "t139",
    "tag": "div",
    "def": "I"
   },
   {
    "k": "t140",
    "tag": "h3",
    "def": "Intelligence Audit"
   },
   {
    "k": "t141",
    "tag": "p",
    "def": "We map your current narrative landscape — what's being said, by whom, where, and at what risk level. No assumptions."
   },
   {
    "k": "t142",
    "tag": "div",
    "def": "II"
   },
   {
    "k": "t143",
    "tag": "h3",
    "def": "Strategy Design"
   },
   {
    "k": "t144",
    "tag": "p",
    "def": "We architect a communication framework tailored to your stakeholders, objectives, and the media environment you operate in."
   },
   {
    "k": "t145",
    "tag": "div",
    "def": "III"
   },
   {
    "k": "t146",
    "tag": "h3",
    "def": "Execution &amp; Deployment"
   },
   {
    "k": "t147",
    "tag": "p",
    "def": "Messaging rollout, media placements, spokesperson training, and crisis response — delivered with newsroom-grade speed and precision."
   },
   {
    "k": "t148",
    "tag": "div",
    "def": "IV"
   },
   {
    "k": "t149",
    "tag": "h3",
    "def": "Monitor &amp; Protect"
   },
   {
    "k": "t150",
    "tag": "p",
    "def": "Ongoing reputation monitoring, rapid rebuttal when needed, and continuous narrative optimization to keep your credibility intact."
   },
   {
    "k": "t151",
    "tag": "p",
    "def": "Where We Operate"
   },
   {
    "k": "t152",
    "tag": "h2",
    "def": "Pakistan · GCC · <em>Beyond</em>"
   },
   {
    "k": "t153",
    "tag": "em",
    "def": "Beyond"
   },
   {
    "k": "t154",
    "tag": "p",
    "def": "Serving organizations that operate in complex, multi-cultural communication environments — locally and across the Gulf."
   },
   {
    "k": "t155",
    "tag": "div",
    "def": "🇵🇰"
   },
   {
    "k": "t156",
    "tag": "p",
    "def": "Pakistan"
   },
   {
    "k": "t157",
    "tag": "p",
    "def": "Deep institutional relationships across government, media, corporate, and civil society. Home base for all crisis response operations."
   },
   {
    "k": "t158",
    "tag": "div",
    "def": "🇸🇦"
   },
   {
    "k": "t159",
    "tag": "p",
    "def": "Saudi Arabia"
   },
   {
    "k": "t160",
    "tag": "p",
    "def": "Published contributor to SRMG — Saudi Research &amp; Media Group, Jeddah. Direct understanding of Vision 2030 communication standards."
   },
   {
    "k": "t161",
    "tag": "div",
    "def": "🇦🇪"
   },
   {
    "k": "t162",
    "tag": "p",
    "def": "UAE"
   },
   {
    "k": "t163",
    "tag": "p",
    "def": "Strategic communication for organizations targeting Dubai and Abu Dhabi's corporate ecosystem. Bilingual narrative capability."
   },
   {
    "k": "t164",
    "tag": "div",
    "def": "🇶🇦"
   },
   {
    "k": "t165",
    "tag": "p",
    "def": "Qatar"
   },
   {
    "k": "t166",
    "tag": "p",
    "def": "Institutional communications aligned with Qatar's rapidly evolving media and governance landscape post-2022."
   },
   {
    "k": "t167",
    "tag": "div",
    "def": "🇰🇼"
   },
   {
    "k": "t168",
    "tag": "p",
    "def": "Kuwait &amp; Bahrain"
   },
   {
    "k": "t169",
    "tag": "p",
    "def": "Corporate and government communications for Gulf-based organizations with Pakistani diaspora audience considerations."
   },
   {
    "k": "t170",
    "tag": "div",
    "def": "🌍"
   },
   {
    "k": "t171",
    "tag": "p",
    "def": "International / Remote"
   },
   {
    "k": "t172",
    "tag": "p",
    "def": "Remote strategic advisory for international organizations, NGOs, and diaspora institutions requiring South Asian and GCC media expertise."
   },
   {
    "k": "t173",
    "tag": "p",
    "def": "Ideal Clients"
   },
   {
    "k": "t174",
    "tag": "h2",
    "def": "Built for Organizations<br/><em>Under Scrutiny</em>"
   },
   {
    "k": "t175",
    "tag": "em",
    "def": "Under Scrutiny"
   },
   {
    "k": "t176",
    "tag": "p",
    "def": "🏢"
   },
   {
    "k": "t177",
    "tag": "p",
    "def": "Corporations"
   },
   {
    "k": "t178",
    "tag": "p",
    "def": "Listed companies, multinationals, conglomerates facing media or reputational risk"
   },
   {
    "k": "t179",
    "tag": "p",
    "def": "🏛️"
   },
   {
    "k": "t180",
    "tag": "p",
    "def": "Government Bodies"
   },
   {
    "k": "t181",
    "tag": "p",
    "def": "Ministries, regulatory authorities, and public institutions requiring narrative control"
   },
   {
    "k": "t182",
    "tag": "p",
    "def": "🎓"
   },
   {
    "k": "t183",
    "tag": "p",
    "def": "Education Institutions"
   },
   {
    "k": "t184",
    "tag": "p",
    "def": "Universities and boards facing accountability journalism or public trust challenges"
   },
   {
    "k": "t185",
    "tag": "p",
    "def": "🏥"
   },
   {
    "k": "t186",
    "tag": "p",
    "def": "Healthcare &amp; NGOs"
   },
   {
    "k": "t187",
    "tag": "p",
    "def": "Crisis messaging, public health communication, and emergency narrative management"
   },
   {
    "k": "t188",
    "tag": "p",
    "def": "👔"
   },
   {
    "k": "t189",
    "tag": "p",
    "def": "Executives &amp; HNIs"
   },
   {
    "k": "t190",
    "tag": "p",
    "def": "Personal reputation management, media presence building, and narrative positioning"
   },
   {
    "k": "t191",
    "tag": "p",
    "def": "🚀"
   },
   {
    "k": "t192",
    "tag": "p",
    "def": "Startups &amp; Scale-ups"
   },
   {
    "k": "t193",
    "tag": "p",
    "def": "Brand communications, investor narrative, and market entry positioning in GCC"
   },
   {
    "k": "t194",
    "tag": "p",
    "def": "Let's Work Together"
   },
   {
    "k": "t195",
    "tag": "h2",
    "def": "Request a<br/><em>Strategy Session</em>"
   },
   {
    "k": "t196",
    "tag": "em",
    "def": "Strategy Session"
   },
   {
    "k": "t197",
    "tag": "p",
    "def": "Phone &amp; WhatsApp"
   },
   {
    "k": "t198",
    "tag": "a",
    "def": "+92 333 292 4941"
   },
   {
    "k": "t199",
    "tag": "p",
    "def": "Email"
   },
   {
    "k": "t200",
    "tag": "a",
    "def": "contact@voiceforte.com"
   },
   {
    "k": "t201",
    "tag": "p",
    "def": "Location"
   },
   {
    "k": "t202",
    "tag": "span",
    "def": "Available on-site GCC · Remote International"
   },
   {
    "k": "t203",
    "tag": "p",
    "def": "Connect"
   },
   {
    "k": "t204",
    "tag": "a",
    "def": "LinkedIn"
   },
   {
    "k": "t205",
    "tag": "a",
    "def": "Instagram"
   },
   {
    "k": "t206",
    "tag": "a",
    "def": "Facebook"
   },
   {
    "k": "t207",
    "tag": "a",
    "def": "TikTok"
   },
   {
    "k": "t208",
    "tag": "label",
    "def": "Full Name *"
   },
   {
    "k": "t209",
    "tag": "label",
    "def": "Organization"
   },
   {
    "k": "t210",
    "tag": "label",
    "def": "Email *"
   },
   {
    "k": "t211",
    "tag": "label",
    "def": "Phone / WhatsApp"
   },
   {
    "k": "t212",
    "tag": "label",
    "def": "Country / Market"
   },
   {
    "k": "t213",
    "tag": "label",
    "def": "Service Required"
   },
   {
    "k": "t214",
    "tag": "label",
    "def": "Describe Your Situation *"
   },
   {
    "k": "t215",
    "tag": "p",
    "def": "✓ Enquiry received. We'll respond within 24 hours."
   },
   {
    "k": "t216",
    "tag": "p",
    "def": "A confirmation has been sent to your email."
   },
   {
    "k": "t217",
    "tag": "button",
    "def": "Send Enquiry →"
   },
   {
    "k": "t218",
    "tag": "p",
    "def": "All enquiries are strictly confidential. Delivered to contact@voiceforte.com · Response within 24 hours."
   },
   {
    "k": "t219",
    "tag": "div",
    "def": "Voice Forte™"
   },
   {
    "k": "t220",
    "tag": "p",
    "def": "Crisis Communication &amp; Strategic Narrative Agency"
   },
   {
    "k": "t221",
    "tag": "p",
    "def": "© 2026 Voice Forte™ · All Rights Reserved · Karachi, Pakistan"
   },
   {
    "k": "t222",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t223",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t224",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t225",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t226",
    "tag": "a",
    "def": "Contact"
   },
   {
    "k": "t227",
    "tag": "span",
    "def": "Chat on WhatsApp"
   }
  ]
 },
 "about": {
  "title": "About",
  "fields": [
   {
    "k": "t1",
    "tag": "span",
    "def": "✕"
   },
   {
    "k": "t2",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t3",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t4",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t5",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t6",
    "tag": "a",
    "def": "Consultation"
   },
   {
    "k": "t7",
    "tag": "p",
    "def": "About Voice Forte™"
   },
   {
    "k": "t8",
    "tag": "h1",
    "def": "Built on journalism.<br/>Designed for <em>crisis-ready</em> communication."
   },
   {
    "k": "t9",
    "tag": "em",
    "def": "crisis-ready"
   },
   {
    "k": "t10",
    "tag": "p",
    "def": "Voice Forte™ is a Crisis Communication &amp; Strategic Narrative Agency powered by 13+ years of newsroom experience, live-crisis reporting, and media intelligence — now applied to protecting the reputations of organizations across Pakistan and the GCC."
   },
   {
    "k": "t11",
    "tag": "p",
    "def": "Our Story"
   },
   {
    "k": "t12",
    "tag": "h2",
    "def": "From frontline journalism to <em>narrative control</em>"
   },
   {
    "k": "t13",
    "tag": "em",
    "def": "narrative control"
   },
   {
    "k": "t14",
    "tag": "h3",
    "def": "Newsroom Foundations (2013 – 2025)"
   },
   {
    "k": "t15",
    "tag": "p",
    "def": "Voice Forte™ is built on real newsroom experience — over a decade reporting live from crisis events, political flashpoints, public health emergencies, and institutional failures across Pakistan, plus published contribution to SRMG (Saudi Research &amp; Media Group, Jeddah)."
   },
   {
    "k": "t16",
    "tag": "p",
    "def": "That frontline experience built a working understanding of how a story actually spreads, who shapes it, and how fast an organization has to move to control it — knowledge no classroom or generalist PR career path teaches firsthand."
   },
   {
    "k": "t17",
    "tag": "h3",
    "def": "The Transition"
   },
   {
    "k": "t18",
    "tag": "p",
    "def": "As digital platforms accelerated how fast a crisis could spread, the natural next step was to bring that same instinct into the boardroom — helping organizations build the crisis-readiness, media discipline, and reputation infrastructure that most institutions only think about after something has already gone wrong."
   },
   {
    "k": "t19",
    "tag": "h3",
    "def": "Today"
   },
   {
    "k": "t20",
    "tag": "p",
    "def": "Voice Forte™ now operates as a Crisis Communication &amp; Strategic Narrative Agency, serving corporate, government, healthcare, and education clients across Pakistan and the GCC — combining crisis response frameworks, executive media training, media relations, and reputation management under one senior advisory practice."
   },
   {
    "k": "t21",
    "tag": "h3",
    "def": "Our Core Identity"
   },
   {
    "k": "t22",
    "tag": "p",
    "def": "<strong>We are not generalist marketers.</strong> We are communication strategists trained in real-time media environments — where narratives shift in minutes and accuracy is the difference between contained damage and a full-blown crisis."
   },
   {
    "k": "t23",
    "tag": "strong",
    "def": "We are not generalist marketers."
   },
   {
    "k": "t24",
    "tag": "p",
    "def": "<strong>Our focus:</strong> Prepare before the crisis → control the narrative during it → rebuild credibility after it."
   },
   {
    "k": "t25",
    "tag": "strong",
    "def": "Our focus:"
   },
   {
    "k": "t26",
    "tag": "p",
    "def": "Mission &amp; Vision"
   },
   {
    "k": "t27",
    "tag": "h2",
    "def": "Why we <em>exist</em>"
   },
   {
    "k": "t28",
    "tag": "em",
    "def": "exist"
   },
   {
    "k": "t29",
    "tag": "h3",
    "def": "Our Mission"
   },
   {
    "k": "t30",
    "tag": "p",
    "def": "To help organizations communicate with clarity, credibility, and speed — before, during, and after moments of reputational pressure — by combining frontline journalism intelligence with disciplined strategic communication systems."
   },
   {
    "k": "t31",
    "tag": "h3",
    "def": "Our Vision"
   },
   {
    "k": "t32",
    "tag": "p",
    "def": "To be the crisis communication practice Pakistan and GCC organizations trust first — the advisor called at 3 AM, not the agency discovered after the story has already broken."
   },
   {
    "k": "t33",
    "tag": "p",
    "def": "Core Values"
   },
   {
    "k": "t34",
    "tag": "h2",
    "def": "Principles that hold under <em>pressure</em>"
   },
   {
    "k": "t35",
    "tag": "em",
    "def": "pressure"
   },
   {
    "k": "t36",
    "tag": "p",
    "def": "01"
   },
   {
    "k": "t37",
    "tag": "h3",
    "def": "Accuracy Under Pressure"
   },
   {
    "k": "t38",
    "tag": "p",
    "def": "Every recommendation is built on the same discipline live breaking news demands: verify first, speak second, never guess in public."
   },
   {
    "k": "t39",
    "tag": "p",
    "def": "02"
   },
   {
    "k": "t40",
    "tag": "h3",
    "def": "Speed With Judgment"
   },
   {
    "k": "t41",
    "tag": "p",
    "def": "In a crisis, silence is a decision too. We move fast — but every message is tested against how a journalist would read it, not just how it sounds internally."
   },
   {
    "k": "t42",
    "tag": "p",
    "def": "03"
   },
   {
    "k": "t43",
    "tag": "h3",
    "def": "Strategy Before Statements"
   },
   {
    "k": "t44",
    "tag": "p",
    "def": "No press release goes out without a narrative framework behind it. Reactive communication without strategy is how crises get worse, not better."
   },
   {
    "k": "t45",
    "tag": "p",
    "def": "Our Team"
   },
   {
    "k": "t46",
    "tag": "h2",
    "def": "The people behind <em>the narrative</em>"
   },
   {
    "k": "t47",
    "tag": "em",
    "def": "the narrative"
   },
   {
    "k": "t48",
    "tag": "h2",
    "def": "Let's build your <em>crisis-ready</em> foundation"
   },
   {
    "k": "t49",
    "tag": "em",
    "def": "crisis-ready"
   },
   {
    "k": "t50",
    "tag": "p",
    "def": "Whether you're preparing before a crisis or managing one in progress, Voice Forte™ helps you control the narrative with newsroom-grade discipline."
   },
   {
    "k": "t51",
    "tag": "a",
    "def": "Request a Strategy Session"
   },
   {
    "k": "t52",
    "tag": "div",
    "def": "Voice Forte™"
   },
   {
    "k": "t53",
    "tag": "p",
    "def": "Crisis Communication &amp; Strategic Narrative Agency"
   },
   {
    "k": "t54",
    "tag": "p",
    "def": "© 2026 Voice Forte™ · All Rights Reserved · Karachi, Pakistan"
   },
   {
    "k": "t55",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t56",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t57",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t58",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t59",
    "tag": "a",
    "def": "Contact"
   },
   {
    "k": "t60",
    "tag": "span",
    "def": "Chat on WhatsApp"
   }
  ]
 },
 "services": {
  "title": "Services",
  "fields": [
   {
    "k": "t1",
    "tag": "span",
    "def": "✕"
   },
   {
    "k": "t2",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t3",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t4",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t5",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t6",
    "tag": "a",
    "def": "Consultation"
   },
   {
    "k": "t7",
    "tag": "p",
    "def": "What We Do"
   },
   {
    "k": "t8",
    "tag": "h1",
    "def": "Services built on <em>newsroom precision</em>"
   },
   {
    "k": "t9",
    "tag": "em",
    "def": "newsroom precision"
   },
   {
    "k": "t10",
    "tag": "p",
    "def": "Every service is rooted in 13+ years of breaking-news experience — where accuracy, speed, and credibility are non-negotiable. From crisis response to executive media training, each engagement is led directly by the founder."
   },
   {
    "k": "t11",
    "tag": "div",
    "def": "01"
   },
   {
    "k": "t12",
    "tag": "div",
    "def": "🛡️"
   },
   {
    "k": "t13",
    "tag": "h3",
    "def": "Crisis Communication Management"
   },
   {
    "k": "t14",
    "tag": "p",
    "def": "When a crisis breaks, every minute counts. We deploy rapid-response messaging frameworks to contain reputational damage, control the information cycle, and restore stakeholder confidence — before the story writes itself."
   },
   {
    "k": "t15",
    "tag": "span",
    "def": "Rapid Response"
   },
   {
    "k": "t16",
    "tag": "span",
    "def": "Dark Site Readiness"
   },
   {
    "k": "t17",
    "tag": "span",
    "def": "Holding Statements"
   },
   {
    "k": "t18",
    "tag": "span",
    "def": "24/7 Advisory"
   },
   {
    "k": "t19",
    "tag": "div",
    "def": "02"
   },
   {
    "k": "t20",
    "tag": "div",
    "def": "📖"
   },
   {
    "k": "t21",
    "tag": "h3",
    "def": "Strategic Narrative Design"
   },
   {
    "k": "t22",
    "tag": "p",
    "def": "Your institution has a story. We ensure it's told with authority. From positioning frameworks to long-form brand journalism, we craft narratives that define how governments, corporations, and executives are perceived."
   },
   {
    "k": "t23",
    "tag": "span",
    "def": "Message Architecture"
   },
   {
    "k": "t24",
    "tag": "span",
    "def": "Brand Journalism"
   },
   {
    "k": "t25",
    "tag": "span",
    "def": "Thought Leadership"
   },
   {
    "k": "t26",
    "tag": "span",
    "def": "Arabic Adaptation"
   },
   {
    "k": "t27",
    "tag": "div",
    "def": "03"
   },
   {
    "k": "t28",
    "tag": "div",
    "def": "🎙️"
   },
   {
    "k": "t29",
    "tag": "h3",
    "def": "Executive Media Training"
   },
   {
    "k": "t30",
    "tag": "p",
    "def": "Trained by a journalist who has interviewed ministers, covered disasters, and conducted investigations — our media training prepares executives for hostile press, live broadcast, and high-stakes stakeholder briefings."
   },
   {
    "k": "t31",
    "tag": "span",
    "def": "Mock Interviews"
   },
   {
    "k": "t32",
    "tag": "span",
    "def": "On-Camera Training"
   },
   {
    "k": "t33",
    "tag": "span",
    "def": "Press Conference Prep"
   },
   {
    "k": "t34",
    "tag": "span",
    "def": "Key Message Drills"
   },
   {
    "k": "t35",
    "tag": "div",
    "def": "04"
   },
   {
    "k": "t36",
    "tag": "div",
    "def": "📰"
   },
   {
    "k": "t37",
    "tag": "h3",
    "def": "Corporate Communications Strategy"
   },
   {
    "k": "t38",
    "tag": "p",
    "def": "We build end-to-end communication ecosystems — internal and external — ensuring your organization speaks with one coherent voice across all channels, audiences, and markets, from Karachi to Riyadh."
   },
   {
    "k": "t39",
    "tag": "span",
    "def": "Communication Audit"
   },
   {
    "k": "t40",
    "tag": "span",
    "def": "Policy Development"
   },
   {
    "k": "t41",
    "tag": "span",
    "def": "Stakeholder Mapping"
   },
   {
    "k": "t42",
    "tag": "span",
    "def": "Multi-Channel Strategy"
   },
   {
    "k": "t43",
    "tag": "div",
    "def": "05"
   },
   {
    "k": "t44",
    "tag": "div",
    "def": "🌐"
   },
   {
    "k": "t45",
    "tag": "h3",
    "def": "Reputation Management &amp; Monitoring"
   },
   {
    "k": "t46",
    "tag": "p",
    "def": "Proactive reputation management that detects threats before they escalate. We monitor media landscapes, identify narrative risks, and build long-term credibility infrastructure for organizations operating in complex environments."
   },
   {
    "k": "t47",
    "tag": "span",
    "def": "Media Monitoring"
   },
   {
    "k": "t48",
    "tag": "span",
    "def": "Sentiment Analysis"
   },
   {
    "k": "t49",
    "tag": "span",
    "def": "Risk Mapping"
   },
   {
    "k": "t50",
    "tag": "span",
    "def": "Counter-Narrative"
   },
   {
    "k": "t51",
    "tag": "div",
    "def": "06"
   },
   {
    "k": "t52",
    "tag": "div",
    "def": "🤝"
   },
   {
    "k": "t53",
    "tag": "h3",
    "def": "Media Relations &amp; Earned Coverage"
   },
   {
    "k": "t54",
    "tag": "p",
    "def": "We leverage 13+ years of journalist relationships across Pakistan's leading broadcast and print media to secure earned coverage — the most credible form of visibility money cannot simply buy."
   },
   {
    "k": "t55",
    "tag": "span",
    "def": "Press Release Strategy"
   },
   {
    "k": "t56",
    "tag": "span",
    "def": "Media Pitching"
   },
   {
    "k": "t57",
    "tag": "span",
    "def": "Broadcast Placement"
   },
   {
    "k": "t58",
    "tag": "span",
    "def": "Editorial Access"
   },
   {
    "k": "t59",
    "tag": "div",
    "def": "07"
   },
   {
    "k": "t60",
    "tag": "div",
    "def": "🏛️"
   },
   {
    "k": "t61",
    "tag": "h3",
    "def": "Public Affairs &amp; Government Relations"
   },
   {
    "k": "t62",
    "tag": "p",
    "def": "Navigating the interface between organizations and government requires credibility on both sides. Our background covering governors, ministers, and regulatory bodies gives us unique insight into institutional communication."
   },
   {
    "k": "t63",
    "tag": "span",
    "def": "Policy Messaging"
   },
   {
    "k": "t64",
    "tag": "span",
    "def": "Regulatory Affairs"
   },
   {
    "k": "t65",
    "tag": "span",
    "def": "Advocacy Communication"
   },
   {
    "k": "t66",
    "tag": "span",
    "def": "Institutional Briefings"
   },
   {
    "k": "t67",
    "tag": "div",
    "def": "08"
   },
   {
    "k": "t68",
    "tag": "div",
    "def": "🔍"
   },
   {
    "k": "t69",
    "tag": "h3",
    "def": "Investigative Intelligence &amp; Due Diligence"
   },
   {
    "k": "t70",
    "tag": "p",
    "def": "We apply the skills of investigative journalism — source development, document analysis, institutional research — to provide organizations with intelligence on reputational risks, third-party exposure, and sector vulnerabilities."
   },
   {
    "k": "t71",
    "tag": "span",
    "def": "Background Research"
   },
   {
    "k": "t72",
    "tag": "span",
    "def": "Risk Assessment"
   },
   {
    "k": "t73",
    "tag": "span",
    "def": "Sector Analysis"
   },
   {
    "k": "t74",
    "tag": "span",
    "def": "Narrative Auditing"
   },
   {
    "k": "t75",
    "tag": "div",
    "def": "09"
   },
   {
    "k": "t76",
    "tag": "div",
    "def": "📱"
   },
   {
    "k": "t77",
    "tag": "h3",
    "def": "Digital &amp; Social Media Communication"
   },
   {
    "k": "t78",
    "tag": "p",
    "def": "Strategic content systems and platform-specific audience engagement — built for the speed and scrutiny of today's information environment while maintaining institutional credibility."
   },
   {
    "k": "t79",
    "tag": "span",
    "def": "Content Strategy"
   },
   {
    "k": "t80",
    "tag": "span",
    "def": "Platform Management"
   },
   {
    "k": "t81",
    "tag": "span",
    "def": "Audience Engagement"
   },
   {
    "k": "t82",
    "tag": "span",
    "def": "Narrative Consistency"
   },
   {
    "k": "t83",
    "tag": "h2",
    "def": "Not sure which service fits your <em>situation</em>?"
   },
   {
    "k": "t84",
    "tag": "em",
    "def": "situation"
   },
   {
    "k": "t85",
    "tag": "p",
    "def": "Every engagement starts with a confidential strategy session to map your actual risk before we recommend anything."
   },
   {
    "k": "t86",
    "tag": "a",
    "def": "Request a Strategy Session"
   },
   {
    "k": "t87",
    "tag": "div",
    "def": "Voice Forte™"
   },
   {
    "k": "t88",
    "tag": "p",
    "def": "Crisis Communication &amp; Strategic Narrative Agency"
   },
   {
    "k": "t89",
    "tag": "p",
    "def": "© 2026 Voice Forte™ · All Rights Reserved · Karachi, Pakistan"
   },
   {
    "k": "t90",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t91",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t92",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t93",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t94",
    "tag": "a",
    "def": "Contact"
   },
   {
    "k": "t95",
    "tag": "span",
    "def": "Chat on WhatsApp"
   }
  ]
 },
 "insights": {
  "title": "Insights",
  "fields": [
   {
    "k": "t1",
    "tag": "span",
    "def": "✕"
   },
   {
    "k": "t2",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t3",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t4",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t5",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t6",
    "tag": "a",
    "def": "Consultation"
   },
   {
    "k": "t7",
    "tag": "p",
    "def": "Crisis &amp; Communication Lab"
   },
   {
    "k": "t8",
    "tag": "h1",
    "def": "Insights from <em>newsroom to boardroom</em>"
   },
   {
    "k": "t9",
    "tag": "em",
    "def": "newsroom to boardroom"
   },
   {
    "k": "t10",
    "tag": "p",
    "def": "Weekly field notes on crisis communication, media strategy, and reputation management — drawn from 13+ years of frontline reporting and real advisory work across Pakistan and the GCC."
   },
   {
    "k": "t11",
    "tag": "button",
    "def": "All Insights"
   },
   {
    "k": "t12",
    "tag": "button",
    "def": "Crisis Communication"
   },
   {
    "k": "t13",
    "tag": "button",
    "def": "Internal Communications"
   },
   {
    "k": "t14",
    "tag": "button",
    "def": "Government &amp; Public Affairs"
   },
   {
    "k": "t15",
    "tag": "button",
    "def": "Media Relations"
   },
   {
    "k": "t16",
    "tag": "p",
    "def": "Crisis Communication"
   },
   {
    "k": "t17",
    "tag": "h3",
    "def": "\"No Comment\" Usually Makes a Crisis Worse — Not Better"
   },
   {
    "k": "t18",
    "tag": "p",
    "def": "In most cases, \"no comment\" doesn't stop a story — it fuels it. Why communication timing matters more than perfection in a crisis, and what journalists actually expect when an organization goes quiet."
   },
   {
    "k": "t19",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t20",
    "tag": "p",
    "def": "Government &amp; Public Affairs"
   },
   {
    "k": "t21",
    "tag": "h3",
    "def": "The Government Crisis Communication Gap"
   },
   {
    "k": "t22",
    "tag": "p",
    "def": "An analysis of the structural gap between routine government communications and true crisis-readiness — and what public institutions consistently get wrong when the pressure is on."
   },
   {
    "k": "t23",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t24",
    "tag": "p",
    "def": "Media Relations"
   },
   {
    "k": "t25",
    "tag": "h3",
    "def": "Why Journalists Make Better PR Professionals Than PR Graduates"
   },
   {
    "k": "t26",
    "tag": "p",
    "def": "Most PR professionals study communication. Journalists live it. On the practical edge that frontline newsroom experience brings to strategic communications work."
   },
   {
    "k": "t27",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t28",
    "tag": "p",
    "def": "Crisis Communication"
   },
   {
    "k": "t29",
    "tag": "h3",
    "def": "The Silence Before the Fever: What Europe's Heatwave Reveals About Crisis Communication Failure"
   },
   {
    "k": "t30",
    "tag": "p",
    "def": "Why temperatures above 50°C are managed safely every year during Hajj, while a 40°C heatwave proved devastating across parts of Europe — and what that gap teaches about risk communication."
   },
   {
    "k": "t31",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t32",
    "tag": "p",
    "def": "Crisis Communication"
   },
   {
    "k": "t33",
    "tag": "h3",
    "def": "They Were Burying Children Every Day — No One Knew Why"
   },
   {
    "k": "t34",
    "tag": "p",
    "def": "A first-hand account from Kemari, January 2023: eighteen deaths before a single official response system was fully activated. What the absence of an early warning system reveals about institutional crisis preparedness."
   },
   {
    "k": "t35",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t36",
    "tag": "p",
    "def": "Internal Communications"
   },
   {
    "k": "t37",
    "tag": "h3",
    "def": "The Cost of Silence Inside Organizations"
   },
   {
    "k": "t38",
    "tag": "p",
    "def": "Why employee silence is a leadership issue, not a content problem — and why every company needs an internal newsletter, even without a design team or a long-term plan."
   },
   {
    "k": "t39",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t40",
    "tag": "p",
    "def": "Crisis Communication"
   },
   {
    "k": "t41",
    "tag": "h3",
    "def": "That Smoke Behind Me Was Not Just a Fire"
   },
   {
    "k": "t42",
    "tag": "p",
    "def": "Live on air, reporting a fire in Karachi — and realizing the real story wasn't the fire, it was the silence before it happened. Why every organization needs a system for pre-crisis communication."
   },
   {
    "k": "t43",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t44",
    "tag": "p",
    "def": "Crisis Communication"
   },
   {
    "k": "t45",
    "tag": "h3",
    "def": "The 3 AM Call Every CEO Dreads"
   },
   {
    "k": "t46",
    "tag": "p",
    "def": "Most organizations don't fail in a crisis because of budget, size, or resources. They fail because they are not prepared. Five signs your organization isn't crisis-ready."
   },
   {
    "k": "t47",
    "tag": "a",
    "def": "Read on LinkedIn →"
   },
   {
    "k": "t48",
    "tag": "h2",
    "def": "Get <em>Crisis &amp; Communication Lab</em> weekly"
   },
   {
    "k": "t49",
    "tag": "em",
    "def": "Crisis &amp; Communication Lab"
   },
   {
    "k": "t50",
    "tag": "p",
    "def": "Real-world insights on crisis communication, media strategy, and reputation management — straight from newsroom experience to your inbox."
   },
   {
    "k": "t51",
    "tag": "a",
    "def": "Subscribe on LinkedIn"
   },
   {
    "k": "t52",
    "tag": "div",
    "def": "Voice Forte™"
   },
   {
    "k": "t53",
    "tag": "p",
    "def": "Crisis Communication &amp; Strategic Narrative Agency"
   },
   {
    "k": "t54",
    "tag": "p",
    "def": "© 2026 Voice Forte™ · All Rights Reserved · Karachi, Pakistan"
   },
   {
    "k": "t55",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t56",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t57",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t58",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t59",
    "tag": "a",
    "def": "Contact"
   },
   {
    "k": "t60",
    "tag": "span",
    "def": "Chat on WhatsApp"
   }
  ]
 },
 "contact": {
  "title": "Contact",
  "fields": [
   {
    "k": "t1",
    "tag": "span",
    "def": "✕"
   },
   {
    "k": "t2",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t3",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t4",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t5",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t6",
    "tag": "a",
    "def": "Consultation"
   },
   {
    "k": "t7",
    "tag": "p",
    "def": "Let's Talk"
   },
   {
    "k": "t8",
    "tag": "h1",
    "def": "Let's control your narrative<br/><em>before someone else does</em>"
   },
   {
    "k": "t9",
    "tag": "em",
    "def": "before someone else does"
   },
   {
    "k": "t10",
    "tag": "p",
    "def": "Voice Forte™ helps brands, leaders, and organizations manage reputation, crisis communication, and strategic media positioning in high-pressure environments. All enquiries are strictly confidential."
   },
   {
    "k": "t11",
    "tag": "p",
    "def": "📞"
   },
   {
    "k": "t12",
    "tag": "p",
    "def": "Direct Call"
   },
   {
    "k": "t13",
    "tag": "p",
    "def": "Immediate consultation for urgent communication or crisis situations."
   },
   {
    "k": "t14",
    "tag": "p",
    "def": "💬"
   },
   {
    "k": "t15",
    "tag": "p",
    "def": "WhatsApp Strategy Line"
   },
   {
    "k": "t16",
    "tag": "p",
    "def": "Fast response for business enquiries and consultation requests."
   },
   {
    "k": "t17",
    "tag": "p",
    "def": "✉️"
   },
   {
    "k": "t18",
    "tag": "p",
    "def": "Email Communication"
   },
   {
    "k": "t19",
    "tag": "p",
    "def": "For corporate proposals, PR planning, and strategic partnerships."
   },
   {
    "k": "t20",
    "tag": "p",
    "def": "Let's Work Together"
   },
   {
    "k": "t21",
    "tag": "h2",
    "def": "Request a<br/><em>Strategy Session</em>"
   },
   {
    "k": "t22",
    "tag": "em",
    "def": "Strategy Session"
   },
   {
    "k": "t23",
    "tag": "p",
    "def": "Phone &amp; WhatsApp"
   },
   {
    "k": "t24",
    "tag": "a",
    "def": "+92 333 292 4941"
   },
   {
    "k": "t25",
    "tag": "p",
    "def": "Email"
   },
   {
    "k": "t26",
    "tag": "a",
    "def": "contact@voiceforte.com"
   },
   {
    "k": "t27",
    "tag": "p",
    "def": "Location"
   },
   {
    "k": "t28",
    "tag": "span",
    "def": "Available on-site GCC · Remote International"
   },
   {
    "k": "t29",
    "tag": "p",
    "def": "Connect"
   },
   {
    "k": "t30",
    "tag": "a",
    "def": "LinkedIn"
   },
   {
    "k": "t31",
    "tag": "a",
    "def": "Instagram"
   },
   {
    "k": "t32",
    "tag": "a",
    "def": "Facebook"
   },
   {
    "k": "t33",
    "tag": "a",
    "def": "TikTok"
   },
   {
    "k": "t34",
    "tag": "label",
    "def": "Full Name *"
   },
   {
    "k": "t35",
    "tag": "label",
    "def": "Organization"
   },
   {
    "k": "t36",
    "tag": "label",
    "def": "Email *"
   },
   {
    "k": "t37",
    "tag": "label",
    "def": "Phone / WhatsApp"
   },
   {
    "k": "t38",
    "tag": "label",
    "def": "Country / Market"
   },
   {
    "k": "t39",
    "tag": "label",
    "def": "Service Required"
   },
   {
    "k": "t40",
    "tag": "label",
    "def": "Describe Your Situation *"
   },
   {
    "k": "t41",
    "tag": "p",
    "def": "✓ Enquiry received. We'll respond within 24 hours."
   },
   {
    "k": "t42",
    "tag": "p",
    "def": "A confirmation has been sent to your email."
   },
   {
    "k": "t43",
    "tag": "button",
    "def": "Send Enquiry →"
   },
   {
    "k": "t44",
    "tag": "p",
    "def": "All enquiries are strictly confidential. Delivered to contact@voiceforte.com · Response within 24 hours."
   },
   {
    "k": "t45",
    "tag": "h2",
    "def": "Need <em>immediate</em> strategic support?"
   },
   {
    "k": "t46",
    "tag": "em",
    "def": "immediate"
   },
   {
    "k": "t47",
    "tag": "p",
    "def": "We handle sensitive communication, media pressure, and reputation-critical situations — reach out directly."
   },
   {
    "k": "t48",
    "tag": "a",
    "def": "Call Now"
   },
   {
    "k": "t49",
    "tag": "a",
    "def": "WhatsApp"
   },
   {
    "k": "t50",
    "tag": "div",
    "def": "Voice Forte™"
   },
   {
    "k": "t51",
    "tag": "p",
    "def": "Crisis Communication &amp; Strategic Narrative Agency"
   },
   {
    "k": "t52",
    "tag": "p",
    "def": "© 2026 Voice Forte™ · All Rights Reserved · Karachi, Pakistan"
   },
   {
    "k": "t53",
    "tag": "a",
    "def": "Home"
   },
   {
    "k": "t54",
    "tag": "a",
    "def": "Services"
   },
   {
    "k": "t55",
    "tag": "a",
    "def": "About"
   },
   {
    "k": "t56",
    "tag": "a",
    "def": "Insights"
   },
   {
    "k": "t57",
    "tag": "a",
    "def": "Contact"
   },
   {
    "k": "t58",
    "tag": "span",
    "def": "Chat on WhatsApp"
   }
  ]
 }
};
