# Tags every editable text element with data-cms="tN" and writes js/cms-schema.js.
# Re-run only if you change page structure (keys follow document order).
import json, re
from bs4 import BeautifulSoup
PAGES = {"index":"Home","about":"About","services":"Services","insights":"Insights","contact":"Contact"}
INLINE = {"em","strong","b","i","br","sup","sub","u","mark"}
SKIP = {"script","style","noscript","svg","title","option","textarea","select","input","html","head","body","path","form"}
schema = {}
for page, title in PAGES.items():
    fn = page + ".html"
    soup = BeautifulSoup(open(fn, encoding="utf-8").read(), "html.parser")
    for e in soup.find_all(attrs={"data-cms": True}): del e["data-cms"]
    fields, n = [], 0
    for e in soup.body.find_all(True):
        if e.name in SKIP or e.find_parent(["nav","script","style","svg","noscript"]): continue
        if any(c.name not in INLINE for c in e.find_all(True)): continue
        inner = e.decode_contents().strip()
        if not e.get_text(strip=True): continue
        n += 1; k = f"t{n}"; e["data-cms"] = k
        fields.append({"k": k, "tag": e.name, "def": inner})
    open(fn, "w", encoding="utf-8").write(str(soup))
    schema[page] = {"title": title, "fields": fields}
    print(page, len(fields))
open("js/cms-schema.js", "w", encoding="utf-8").write("// Auto-generated by tools/tag_pages.py\nexport const SCHEMA = " + json.dumps(schema, ensure_ascii=False, indent=1) + ";\n")
